FROM debian:bookworm-20230502-slim
WORKDIR /app
RUN apt-get update \
    && apt-get install -y dumb-init \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./target/release/rust_example .
EXPOSE 7000
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/app/rust_example"]
