---
name: Build
on:
  pull_request:
    paths:
      - "rust_example/**"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: debian:bookworm-20230502-slim
    defaults:
      run:
        shell: bash
        working-directory: ./rust_example

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
        with:
          path: ./rust_example/.tool-versions

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: ${{ steps.versions.outputs.rust }}

      - name: Build release
        run: cargo build --release

      - name: Build docker container
        run: docker build -f Dockerfile.ghactions -t rust_example .

      - name: Start container
        run: |
          docker run -d -p 7000:7000 rust_example

      - name: Test
        run: |
          curl localhost:7000/hello/friend


